apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: aa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa
  labels:
    app: aa
    service: aa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aa
      service: aa
  template:
    metadata:
      labels:
        app: aa
        service: aa
    spec:
      serviceAccountName: aa
      
      containers:
      - name: aa-container
        image: hhana982/aa:1.<version>
        ports:
        - containerPort: 5000
        
        env: 