apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: aa-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa-db
  labels:
    app: aa-db
    service: aa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aa-db
      service: aa
  template:
    metadata:
      labels:
        app: aa-db
        service: aa
    spec:
      serviceAccountName: aa-db
      volumes:
      - name: aa-db-volume
        persistentVolumeClaim:
          claimName: aa-db
      containers:
      - name: aa-db-container
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql"
          name: aa-db-volume
        env: 
        - name: POSTGRES_PASSWORD
          value: "aa"