apiVersion: v1
kind: Service
metadata:
  name: aa-db
  labels:
    app: aa-db
    service: aa
spec:
  selector:
    app: aa-db
    service: aa
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP